name: run on reusing workflow

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  go-lint:
    uses: kounoike-golangci-bug-reproduction-test/github-workflows/.github/workflows/go-lint.yml@main
